---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: influx
    protocol: TCP
    port: 8086
    targetPort: 8086
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
