apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: {{ .Release.Name }}-pvc
        - name: grafana
          image: grafana/grafana:4.1.2
          imagePullPolicy: Always
          env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: {{ .Release.Name }}-pvc
  volumeClaimTemplates:
    - metadata:
       name: {{ .Release.Name }}-pvc
       annotations:
        volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
